SELECT 
    s.COLUMN_NAME AS SOURCE_COLUMN, 
    s.DATA_TYPE AS SOURCE_TYPE, 
    d.COLUMN_NAME AS DEST_COLUMN, 
    d.DATA_TYPE AS DEST_TYPE,
    case when s.DATA_TYPE = d.DATA_TYPE then 'Match' else 'Mismatch' end as TYPE_COMPARISON
FROM INFORMATION_SCHEMA.COLUMNS s
JOIN INFORMATION_SCHEMA.COLUMNS d
ON s.COLUMN_NAME = d.COLUMN_NAME
WHERE s.TABLE_NAME = 'SOURCE_TABLE' 
AND d.TABLE_NAME = 'DESTINATION_TABLE';
